import { FileText, CheckCircle, AlertTriangle, User, BrainCircuit, Eye } from 'lucide-react';

export default function HRReport({ report, history, proctorEvents }: { report: any, history: any[], proctorEvents: any[] }) {
  if (!report) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center flex-col gap-4">
        <div className="w-16 h-16 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin" />
        <p className="text-slate-600 font-medium">AI is generating the evaluation report...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 p-8">
      <div className="max-w-5xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold text-slate-900">Interview Evaluation Report</h1>
            <p className="text-slate-500 mt-1">Generated by AI Interviewer Pro</p>
          </div>
          <div className="flex items-center gap-3 bg-white px-4 py-2 rounded-xl shadow-sm border border-slate-200">
            <div className="w-12 h-12 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 font-bold text-xl">
              {report.overallScore}
            </div>
            <div className="text-sm">
              <p className="text-slate-500 font-medium">Overall Score</p>
              <p className="text-slate-900 font-bold">out of 100</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-6 mb-6">
          <div className="col-span-2 space-y-6">
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
              <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                <User className="w-5 h-5 text-indigo-600" /> Candidate Summary
              </h2>
              <p className="text-slate-700 leading-relaxed">{report.summary}</p>
            </div>

            <div className="grid grid-cols-2 gap-6">
              <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-emerald-500" /> Strengths
                </h2>
                <ul className="space-y-2">
                  {report.strengths?.map((s: string, i: number) => (
                    <li key={i} className="flex items-start gap-2 text-slate-700 text-sm">
                      <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 shrink-0" />
                      {s}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
                <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5 text-amber-500" /> Areas for Improvement
                </h2>
                <ul className="space-y-2">
                  {report.weaknesses?.map((w: string, i: number) => (
                    <li key={i} className="flex items-start gap-2 text-slate-700 text-sm">
                      <div className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-1.5 shrink-0" />
                      {w}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
              <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                <FileText className="w-5 h-5 text-indigo-600" /> Interview Transcript
              </h2>
              <div className="space-y-4">
                {history.map((h, i) => (
                  <div key={i} className="border-b border-slate-100 pb-4 last:border-0 last:pb-0">
                    <p className="font-medium text-slate-900 text-sm mb-2">Q{i+1}: {h.q}</p>
                    <p className="text-slate-600 text-sm pl-4 border-l-2 border-indigo-200 leading-relaxed">{h.a}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
              <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
                <BrainCircuit className="w-5 h-5 text-indigo-600" /> AI Recommendation
              </h2>
              <div className={`p-4 rounded-xl font-bold text-center text-lg ${
                report.recommendation?.toLowerCase().includes('hire') || report.recommendation?.toLowerCase().includes('proceed') 
                  ? 'bg-emerald-50 text-emerald-700 border border-emerald-200' 
                  : 'bg-amber-50 text-amber-700 border border-amber-200'
              }`}>
                {report.recommendation}
              </div>
              
              <div className="mt-6">
                <h3 className="text-sm font-bold text-slate-900 mb-2">Communication Skills</h3>
                <p className="text-sm text-slate-600">{report.communicationSkills}</p>
              </div>
            </div>

            <div className="bg-slate-900 p-6 rounded-2xl shadow-sm text-white">
              <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
                <Eye className="w-5 h-5 text-emerald-400" /> Proctoring Log
              </h2>
              <div className="space-y-3 text-sm">
                <div className="flex justify-between items-center pb-2 border-b border-slate-800">
                  <span className="text-slate-400">Identity Verification</span>
                  <span className="text-emerald-400 font-medium">Passed</span>
                </div>
                <div className="flex justify-between items-center pb-2 border-b border-slate-800">
                  <span className="text-slate-400">Tab Switches</span>
                  <span className={proctorEvents.filter(e => e.type === 'Tab Switched').length > 0 ? "text-amber-400 font-medium" : "text-emerald-400 font-medium"}>
                    {proctorEvents.filter(e => e.type === 'Tab Switched').length} detected
                  </span>
                </div>
                <div className="flex justify-between items-center pb-2 border-b border-slate-800">
                  <span className="text-slate-400">Gaze Deviations</span>
                  <span className={proctorEvents.filter(e => e.type === 'Gaze Deviated').length > 0 ? "text-amber-400 font-medium" : "text-emerald-400 font-medium"}>
                    {proctorEvents.filter(e => e.type === 'Gaze Deviated').length} detected
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-slate-400">Suspicious Audio</span>
                  <span className="text-emerald-400 font-medium">None</span>
                </div>
              </div>
              
              {proctorEvents.length > 0 && (
                <div className="mt-4 pt-4 border-t border-slate-800">
                  <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Event Timeline</h3>
                  <div className="space-y-2 max-h-32 overflow-y-auto pr-2">
                    {proctorEvents.map((e, i) => (
                      <div key={i} className="flex items-center gap-2 text-xs">
                        <span className="text-slate-500">{e.time}</span>
                        <span className="text-amber-400">{e.type}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
